### ISSUE TITLE
remove non-banner specific CSS rules from banners.css

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-web-services/ucsf_identity_web_banner_templates#11]
see https://github.com/ucsf-web-services/ucsf_identity_web_banner_templates/blob/1.1/banners.css

``` css
body {
background: #fff;
padding: 0;
margin: 0;
}
pre {
background: #fff;
border: 1px inset #ccc;
padding: 3px;
width: 300px;
margin-left: 30px;
margin-right: 30px;
}
```

_DAFUQ?!_ _remove this._
