### ISSUE TITLE
Helvetica Neue is a lie

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-web-services/ucsf_identity_web_banner_templates#23]
See [banners.css](https://github.com/ucsf-web-services/ucsf_identity_web_banner_templates/blob/1.2/banners.css#L8):

``` css
#ucsf-banner-nav {
background: #052049;
height: 32px;
font-family: "Helvetica Neue", "arial", sans-serif;
font-size: 14px;
text-align: center;
width: 100%;
}
```

![lie!](http://i0.kym-cdn.com/photos/images/newsfeed/000/115/357/portal-cake.jpg?1318992465)

Webfonts, please!
